import { Router } from "express";
import absensiRoutes from "../modules/absensi/absensi.routes";
import pegawaiRoutes from "../modules/master-data/pegawai/pegawai.routes";
import jabatanRoutes from "../modules/master-data/jabatan/jabatan.routes";
// import authRoutes from "../modules/auth/auth.routes";
import golonganRoutes from "../modules/master-data/golongan/golongan.routes";
import konfigurasiRoutes from "../modules/payroll/konfigurasi/konfigurasi.routes";
import gajiRoutes from "../modules/payroll/gaji/gaji.routes";
import potonganRoutes from "../modules/payroll/potongan/potongan.routes";
import periodeRoutes from "../modules/periode/periode.routes";
import tunjanganRoutes from "../modules/payroll/tunjangan/tunjangan.routes";
import tunjanganBulananRoutes from "../modules/payroll/tunjangan-bulanan/tunjangan-bulanan.routes";
const router = Router();

router.use("/absensi", absensiRoutes);
router.use("/pegawai", pegawaiRoutes);
router.use("/jabatan", jabatanRoutes);
router.use("/golongan", golonganRoutes);
router.use("/konfigurasi", konfigurasiRoutes);
router.use("/gaji", gajiRoutes);
router.use("/potongan", potonganRoutes);
router.use("/periode", periodeRoutes);
router.use("/tunjangan", tunjanganRoutes);
router.use("/tunjangan_bulanan", tunjanganBulananRoutes);
export default router;
